### PR TITLE
Conform WebSocketHTTPHandler to RFC 6455 section 4.2.1

### PR DESCRIPTION
**Pull request by stackotter**
[RFC 6455 section 4.2.1](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1) prescribes which headers are mandatory for a WebSocket handshake request to be correct. It also details what each of these headers should contain. This PR brings `WebSocketHTTPHander` up to spec (which has a typo by the way, but I didn't change that to keep this PR focussed).

I have documented the new code in a way that makes it easy to match up each check with its corresponding RFC rule (see `WebSocketHTTPHander.verifyHandshakeRequestHeaders`).

There is one conundrum that I ran into while implementing the checks, which is that rule 1 mandates that websocket connections must begin as `GET` requests, however in FlyingFox the method for websocket endpoints is up to users of the framework. We could add some kind of check to `appendRoute`, or we could just leave it given that developers will probably realise pretty quickly that their websocket won't work as a `POST` endpoint. Another option would be creating a separate method for hosting websocket endpoints such as `appendWebSocketRoute` which takes only a path and doesn't let developers specify the method.

### CODE REVIEW

**Comment by stackotter** [comment]
I also added a test for the new checks, but it would probably be better if I split it into a test per rule (and updated it to use validateHandshakeRequestHeaders now that I've refactored through checks into their own function).

**Review by swhitty — APPROVED** [review]
Looks great. Thank you for these RFC fixes.

A month ago I had no idea how websockets actually worked so this really helps 🙏🏻.

**Comment by swhitty** [comment]
RE: the requirement for Sockets requiring the `GET` HTTPMethod.  I do think it is probably OK to allow developers to choose the HTTP Method, even if it is not compliant. We could use `HTTPLogger` to output a warning.

One use case I have for FlyingFox is to assist within testing. `WebSocketHTTPHandler*` should be as close to RFC compliant as possible, but I see some utility in allowing any `HTTPHander` to switch to a web socket connection.

**Comment by swhitty** [comment]
And I have renamed the handler [here](https://github.com/swhitty/FlyingFox/pull/30).

**Comment by stackotter** [comment]
> Looks great. Thank you for these RFC fixes.
> 
> A month ago I had no idea how websockets actually worked so this really helps 🙏🏻.

You're welcome! While reading through the RFC I also found out that I had no idea how it actually worked hahah, there's certainly a lot to learn by reading the RFC documents, but I will admit that they can be quite bland sometimes. I never knew that websocket connections started as HTTP requests and then switched, the more you know.

**Comment by stackotter** [comment]
> RE: the requirement for WebSockets requiring the `GET` HTTPMethod. I do think it is probably OK to allow developers to choose the HTTP Method, even if it is not compliant. We could use `HTTPLogger` to output a warning.
> 
> One use case I have for FlyingFox is to assist within testing. `WebSocketHTTPHandler*` should be as close to RFC compliant as possible, but I see some utility in allowing any `HTTPHandler` to switch to a web socket connection.

I agree with that reasoning, I don't see any issues with straying from the RFC in that regard 👍

**Pull request merged**
